pharmacy_mgmt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 0.tcp.in.ngrok.io
      user: postgres
      password: postgres
      dbname: dbt_tutorial
      schema: public
      threads: 1
