Propharma:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      port: 5432
      password: postgres
      dbname: propharma
      schema: public
      threads: 1
